#!/bin/bash
#
# This script resets the repository to a clean state for testing, focusing only on
# files and directories generated by the build and test scripts.
#
# Usage: reset-test-environment.sh [COMMIT_REF]
#   COMMIT_REF: Optional commit to restore from (default: HEAD)
#

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_ROOT_DIR=$(realpath "${SCRIPT_DIR}/..")
RESTORE_FROM="${1:-HEAD}"

# Run from the repo root
cd "${REPO_ROOT_DIR}"

echo "--> Resetting test environment..."

# 1. Remove all generated files and directories, both tracked and untracked.
#    This ensures we start from a completely clean slate regarding artifacts.
echo "  - Removing generated files and directories..."
rm -rf \
    catalog-*/ \
    catalog-template-4-*.yaml \
    catalog-4-*.yaml \
    test_catalog_template*.yaml \
    original_catalog_template*.yaml \
    registry.redhat.io_* \
    submariner-catalog-config-*.yaml \
    tmp.*

# 2. Restore the specific tracked files that were deleted by the rm command above,
#    and revert any changes to catalog-template.yaml. This does not affect
#    any other work-in-progress files in the repository.
echo "  - Restoring tracked files modified by tests (from ${RESTORE_FROM})..."
# We explicitly list the directories because a glob (catalog-*/) would fail if
# the directories don't exist on the filesystem after the rm.
git restore --source="$RESTORE_FROM" catalog-template.yaml \
    catalog-4-14 \
    catalog-4-15 \
    catalog-4-16 \
    catalog-4-17 \
    catalog-4-18 \
    catalog-4-19 \
    catalog-4-20 \
    catalog-4-21 \
    extracted-catalogs

echo "  - Reset complete."
