#!/bin/bash
#
# This script resets the repository to a clean state for testing, focusing only on
# files and directories generated by the build and test scripts.
#
# Usage: reset-test-environment.sh [COMMIT_REF]
#   COMMIT_REF: Optional commit to restore from (default: HEAD)
#

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_ROOT_DIR=$(realpath "${SCRIPT_DIR}/..")
RESTORE_FROM="${1:-HEAD}"

# Run from the repo root
cd "${REPO_ROOT_DIR}"

if [ "${FBC_TEST_SANDBOX:-}" != "$REPO_ROOT_DIR" ] || [ ! -f .fbc-test-sandbox ]; then
  echo "Refusing to reset a working checkout. Tests create their own candidate sandbox." >&2
  exit 1
fi

echo "--> Resetting test environment..."

# 1. Remove all generated files and directories, both tracked and untracked.
#    This ensures we start from a completely clean slate regarding artifacts.
echo "  - Removing generated files and directories..."
rm -rf \
    catalog-*/ \
    catalog-template-*-*.yaml \
    catalog-*-*.yaml \
    test_catalog_template*.yaml \
    original_catalog_template*.yaml \
    registry.redhat.io_* \
    submariner-catalog-config-*.yaml \
    extracted-catalogs/ \
    tmp.*

# 2. Restore the specific tracked files that were deleted by the rm command above,
#    and revert any changes to catalog-template.yaml. This does not affect
#    any other work-in-progress files in the repository.
echo "  - Restoring tracked files modified by tests (from ${RESTORE_FROM})..."
# Dynamically discover catalog directories from git instead of hardcoding,
# so new OCP versions are automatically included in test cleanup.
CATALOG_DIRS=$(git ls-tree --name-only "$RESTORE_FROM" | grep '^catalog-' || true)
# shellcheck disable=SC2086
git restore --source="$RESTORE_FROM" catalog-template.yaml \
    .tekton/images-mirror-set.yaml \
    $CATALOG_DIRS

echo "  - Reset complete."
