name: Run Test Script

on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y podman git wget jq
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
    - name: Run test script
      run: ./build/test.sh
