---
name: Tests
'on':
  push:
    branches:
      - main
  pull_request:
permissions: {}
jobs:
  test:
    name: Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        env:
          SKIP_AUTH_TESTS: true
        run: make test
