---
name: Validate Catalogs
'on':
  push:
    branches:
      - main
  pull_request:
permissions: {}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman git wget jq
          url=https://github.com/mikefarah/yq/releases/latest/download
          sudo wget -qO /usr/bin/yq ${url}/yq_linux_amd64
          sudo chmod +x /usr/bin/yq
      - name: Validate catalogs
        run: make validate-catalogs
